apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  #type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.exporter.enabled }}
    - port: {{ .Values.exporter.service.port }}
      targetPort: exporter
      protocol: TCP
      name: exporter
    {{- end }}
  selector:
    {{- include "deployment.selectorLabels" . | nindent 4 }}
